# Generated by Django 3.2.7 on 2021-11-17 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pizza_topping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championed_by', to='main.pizza')),
                ('pizzas', models.ManyToManyField(related_name='restaurants', to='main.Pizza')),
            ],
        ),
    ]
